name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Runtime
        uses: oven-sh/setup-bun
        with:
          cache: true

      - name: Build
        run: |
          bun install
          bun bun --use next
          bun run export
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out

